### ISSUE TITLE
python viewinfo.py   ERROR!

### ISSUE THREAD

**Issue by senadaruc** [geekworm-com/UPS2#7]
pi@dhcp% python viewinfo.py 
Traceback (most recent call last):
  File "viewinfo.py", line 408, in <module>
    writeCap(MY_BATTERY_CAP)
  File "viewinfo.py", line 270, in writeCap
    bus.write_byte_data(BQ27441_I2C_ADDRESS,0x60,new_checksum) #trying to write on BlockDataChecksum(self) 
IOError: [Errno 121] Remote I/O error
pi@dhcp%

**Comment by rsotomayor** [comment]
The Same Error !! PleaseHelp


pi@rpidesktop:~ $ sudo i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- 55 -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --                         
pi@rpidesktop:~ $ ./viewinfo.py 
Traceback (most recent call last):
  File "./viewinfo.py", line 409, in <module>
    writeCap(MY_BATTERY_CAP)
  File "./viewinfo.py", line 271, in writeCap
    bus.write_byte_data(BQ27441_I2C_ADDRESS,0x60,new_checksum) #trying to write on BlockDataChecksum(self) 
IOError: [Errno 121] Remote I/O error
pi@rpidesktop:~ $ 
pi@rpidesktop:~ $ 
pi@rpidesktop:~ $ 
pi@rpidesktop:~ $ sudo ./viewinfo.py 
Traceback (most recent call last):
  File "./viewinfo.py", line 409, in <module>
    writeCap(MY_BATTERY_CAP)
  File "./viewinfo.py", line 271, in writeCap
    bus.write_byte_data(BQ27441_I2C_ADDRESS,0x60,new_checksum) #trying to write on BlockDataChecksum(self) 
IOError: [Errno 121] Remote I/O error

**Comment by aioros74** [comment]
There is an i2c timing issue when performing line 259:
block=bus.read_i2c_block_data(BQ27441_I2C_ADDRESS,BQ27441_EXTENDED_BLOCKDATA,32)
The return data "block" start at address "BQ27441_EXTENDED_BLOCKDATA+1" instead of "BQ27441_EXTENDED_BLOCKDATA".
Then, the computed checksum is wrong and writing the wrong checksum lead to the following error:

"bus.write_byte_data(BQ27441_I2C_ADDRESS,0x60,new_checksum) #trying to write on BlockDataChecksum(self)
IOError: [Errno 121] Remote I/O error"

To solve the problem, add a "sleep" before line 259. (time.sleep(1) )
